# Generated by Django 3.1.7 on 2021-04-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='a', upload_to='photos = '),
            preserve_default=False,
        ),
    ]
