# Generated by Django 3.1.7 on 2021-04-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_auto_20210405_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_title'], 'verbose_name_plural': 'PRODUCTS'},
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Size',
            field=models.CharField(choices=[('XS', 'ExtraSmall'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'ExtraLarge'), ('xxl', 'VeryLarge')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.product_category'),
        ),
    ]
