# Generated by Django 3.1.7 on 2021-04-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_auto_20210405_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_category',
        ),
    ]
