# Generated by Django 3.1.7 on 2021-04-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0006_remove_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Size',
            field=models.CharField(blank=True, choices=[('XS', 'ExtraSmall'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'ExtraLarge'), ('xxl', 'VeryLarge')], max_length=10, null=True),
        ),
    ]
