# Generated by Django 3.1.7 on 2021-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_auto_20210405_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'MANUFACTURER',
                'ordering': ['Manufacturer_name'],
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('packaging_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.manufacturer')),
            ],
        ),
    ]
