# Generated by Django 3.1.7 on 2021-04-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_manufacturer_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['manufacturer_name'], 'verbose_name_plural': 'SKU'},
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='manufacturer',
            new_name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='sku',
            name='product_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modelapp.product'),
            preserve_default=False,
        ),
    ]
