# Generated by Django 3.1.7 on 2021-04-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0009_auto_20210405_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.product'),
        ),
    ]
