# Generated by Django 3.1.7 on 2021-04-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0011_auto_20210405_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'plural'},
        ),
    ]
